### ISSUE TITLE
FIFO_DATA_REG_ADDR used in readXYZAxisResultDataFromFIFO AND in readXYZAxisResultData

### ISSUE THREAD

**Issue by Mads-hg** [Seeed-Studio/Seeed_ADXL357B#1]
Hi,

FIFO_DATA_REG_ADDR (0x11) is used both in "readXYZAxisResultDataFromFIFO" and in "readXYZAxisResultData." I believe X_DATA_REG_ADDR (0x08) should have been used in the latter instead.

Please correct me if I'm wrong.

/Mads

**Comment by wujiang** [comment]
@Mads-hg did you test with your suggestion? I found that the z reading from `readXYZAxisResultData` is around `1g` without any movement.

**Comment by wujiang** [comment]
hmm, looks like the code is correct. It should read from `0x11` to get all 3 axises. `0x08` is only X's data register.
<img width="727" alt="Screen Shot 2021-03-18 at 4 56 06 PM" src="https://user-images.githubusercontent.com/77030/111696723-067ff900-880b-11eb-8431-b030ca06427d.png">

**Comment by baorepo** [comment]
OK
